export const attributes = {
  popcorn: [{trait_type: 'Type', value: 'Snack'}],
  bananas: [{trait_type: 'Type', value: 'Snack'}],
  beer: [{trait_type: 'Type', value: 'Beverage'}],
  'bread-slice': [{trait_type: 'Type', value: 'Snack'}],
  'hot-dog': [{trait_type: 'Type', value: 'Meal'}],
  lollipop: [{trait_type: 'Type', value: 'Candy'}],
  milk: [{trait_type: 'Type', value: 'Beverage'}],
  candy: [{trait_type: 'Type', value: 'Candy'}],
  taco: [{trait_type: 'Type', value: 'Meal'}],
  cheese: [{trait_type: 'Type', value: 'Snack'}],
  chicken: [{trait_type: 'Type', value: 'Meal'}],
  soda: [{trait_type: 'Type', value: 'Beverage'}],
  chips: [{trait_type: 'Type', value: 'Snack'}],
  coffee: [{trait_type: 'Type', value: 'Beverage'}],
  pie: [{trait_type: 'Type', value: 'Snack'}],
  donut: [{trait_type: 'Type', value: 'Snack'}],
  egg: [{trait_type: 'Type', value: 'Meal'}],
  fries: [{trait_type: 'Type', value: 'Meal'}],
  hamburger: [{trait_type: 'Type', value: 'Meal'}],
  pizza: [{trait_type: 'Type', value: 'Meal'}],
}

export const labels = [
  "Popcorn",
  "Banana",
  "Beer",
  "Bread",
  "Hot Dog",
  "Lollipop",
  "Milk",
  "Candy",
  "Taco",
  "Cheese",
  "Chicken",
  "Soda",
  "Chips",
  "Coffee",
  "Pie",
  "Donut",
  "Eggs",
  "Fries",
  "Hamburger",
  'Pizza'
] as const;


export const images = [
  'popcorn',
  'bananas',
  'beer',
  'bread-slice',
  'hot-dog',
  'lollipop',
  'milk',
  'candy',
  'taco',
  'cheese',
  'chicken',
  'soda',
  'chips',
  'coffee',
  'pie',
  'donut',
  'egg',
  'fries',
  'hamburger',
  'pizza',


  // 'bread',
  // 'cabbage',
  // 'candy-canes',
  // 'canned-fish', 
  // 'cupcake',
  // 'honey',
  // 'meat',
  // 'mushrooms',
  // 'popcorn',
  // 'rice',
  // 'salt',
  // 'sandwich',
  // 'soda',
  // 'taco',
  // 'watermelon',
] as const
