/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  Foods,
  FoodsInstance,
  VendingMachine,
  VendingMachineInstance,
} from ".";
import { default as testnetDeployments } from "../.deployments.testnet.json";
import { default as devnetDeployments } from "../.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    Foods?: DeployContractExecutionResult<FoodsInstance>;
    VendingMachine?: DeployContractExecutionResult<VendingMachineInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    Foods:
      json.contracts["Foods"] === undefined
        ? undefined
        : {
            ...json.contracts["Foods"],
            contractInstance: Foods.at(
              json.contracts["Foods"].contractInstance.address
            ),
          },
    VendingMachine:
      json.contracts["VendingMachine"] === undefined
        ? undefined
        : {
            ...json.contracts["VendingMachine"],
            contractInstance: VendingMachine.at(
              json.contracts["VendingMachine"].contractInstance.address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
