/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as FoodsContractJson } from "../Foods.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace FoodsTypes {
  export type Fields = {
    tokenUri: HexString;
    collectionId: HexString;
    nftIndex: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
    getNFTIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<FoodsInstance, FoodsTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as FoodsTypes.Fields;
  }

  at(address: string): FoodsInstance {
    return new FoodsInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<TestContractParams<FoodsTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: Omit<TestContractParams<FoodsTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<[HexString, bigint]>> => {
      return testMethod(this, "getCollectionIndex", params);
    },
    getNFTIndex: async (
      params: Omit<TestContractParams<FoodsTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getNFTIndex", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Foods = new Factory(
  Contract.fromJson(
    FoodsContractJson,
    "",
    "7386b370672aff98393754e2785b59018eed34a07e7a7eab3d18b4289f627b72"
  )
);

// Use this class to interact with the blockchain
export class FoodsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FoodsTypes.State> {
    return fetchContractState(Foods, this);
  }

  methods = {
    getTokenUri: async (
      params?: FoodsTypes.CallMethodParams<"getTokenUri">
    ): Promise<FoodsTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        Foods,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: FoodsTypes.CallMethodParams<"getCollectionIndex">
    ): Promise<FoodsTypes.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        Foods,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params?: FoodsTypes.CallMethodParams<"getNFTIndex">
    ): Promise<FoodsTypes.CallMethodResult<"getNFTIndex">> => {
      return callMethod(
        Foods,
        this,
        "getNFTIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends FoodsTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FoodsTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Foods,
      this,
      calls,
      getContractByCodeHash
    )) as FoodsTypes.MultiCallResults<Calls>;
  }
}
