// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Block */
export type BlockId = string & { __brand: 'BlockId' };

/** Represents the table public.Block */
export default interface BlockTable {
  id: ColumnType<BlockId, BlockId | undefined, BlockId>;

  hash: ColumnType<string, string, string>;

  height: ColumnType<bigint, bigint, bigint>;

  timestamp: ColumnType<Date, Date | string, Date | string>;

  chainFrom: ColumnType<number, number, number>;

  chainTo: ColumnType<number, number, number>;

  transactionCount: ColumnType<number, number, number>;
}

export type Block = Selectable<BlockTable>;

export type NewBlock = Insertable<BlockTable>;

export type BlockUpdate = Updateable<BlockTable>;
