// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Pool */
export type PoolId = string & { __brand: 'PoolId' };

/** Represents the table public.Pool */
export default interface PoolTable {
  id: ColumnType<PoolId, PoolId | undefined, PoolId>;

  factory: ColumnType<string, string, string>;

  pair: ColumnType<string, string, string>;

  token0: ColumnType<string, string, string>;

  token1: ColumnType<string, string, string>;
}

export type Pool = Selectable<PoolTable>;

export type NewPool = Insertable<PoolTable>;

export type PoolUpdate = Updateable<PoolTable>;
