// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Account */
export type AccountId = string & { __brand: 'AccountId' };

/** Represents the table public.Account */
export default interface AccountTable {
  id: ColumnType<AccountId, AccountId | undefined, AccountId>;

  userId: ColumnType<UserId, UserId, UserId>;

  type: ColumnType<string, string, string>;

  provider: ColumnType<string, string, string>;

  providerAccountId: ColumnType<string, string, string>;

  refresh_token: ColumnType<string | null, string | null, string | null>;

  access_token: ColumnType<string | null, string | null, string | null>;

  expires_at: ColumnType<bigint | null, bigint | null, bigint | null>;

  token_type: ColumnType<string | null, string | null, string | null>;

  scope: ColumnType<string | null, string | null, string | null>;

  id_token: ColumnType<string | null, string | null, string | null>;

  session_state: ColumnType<string | null, string | null, string | null>;
}

export type Account = Selectable<AccountTable>;

export type NewAccount = Insertable<AccountTable>;

export type AccountUpdate = Updateable<AccountTable>;
