// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.AyinSwap */
export type AyinSwapId = string & { __brand: 'AyinSwapId' };

/** Represents the table public.AyinSwap */
export default interface AyinSwapTable {
  id: ColumnType<AyinSwapId, AyinSwapId | undefined, AyinSwapId>;

  userAddress: ColumnType<string, string, string>;

  pairAddress: ColumnType<string, string, string>;

  amount0: ColumnType<bigint, bigint, bigint>;

  amount1: ColumnType<bigint, bigint, bigint>;

  timestamp: ColumnType<Date, Date | string, Date | string>;

  transactionHash: ColumnType<string, string, string>;
}

export type AyinSwap = Selectable<AyinSwapTable>;

export type NewAyinSwap = Insertable<AyinSwapTable>;

export type AyinSwapUpdate = Updateable<AyinSwapTable>;
