// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Nonce */
export type NonceId = string & { __brand: 'NonceId' };

/** Represents the table public.Nonce */
export default interface NonceTable {
  id: ColumnType<NonceId, NonceId | undefined, NonceId>;

  version: ColumnType<number, number, number>;

  userId: ColumnType<UserId, UserId, UserId>;

  nonce: ColumnType<string, string, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  deletedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Nonce = Selectable<NonceTable>;

export type NewNonce = Insertable<NonceTable>;

export type NonceUpdate = Updateable<NonceTable>;
