// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.PluginLog */
export type PluginLogId = string & { __brand: 'PluginLogId' };

/** Represents the table public.PluginLog */
export default interface PluginLogTable {
  id: ColumnType<PluginLogId, PluginLogId | undefined, PluginLogId>;

  pluginName: ColumnType<string, string, string>;

  blockHash: ColumnType<string, string, string>;
}

export type PluginLog = Selectable<PluginLogTable>;

export type NewPluginLog = Insertable<PluginLogTable>;

export type PluginLogUpdate = Updateable<PluginLogTable>;
