// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as KyselyMigrationTable } from './KyselyMigration';
import { type default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import { type default as BlockTable } from './Block';
import { type default as PluginTable } from './Plugin';
import { type default as PoolTable } from './Pool';
import { type default as TokenTable } from './Token';
import { type default as PluginLogTable } from './PluginLog';
import { type default as AyinReserveTable } from './AyinReserve';
import { type default as AyinLiquidityEventTable } from './AyinLiquidityEvent';
import { type default as AyinSwapTable } from './AyinSwap';

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  Block: BlockTable;

  Plugin: PluginTable;

  Pool: PoolTable;

  Token: TokenTable;

  PluginLog: PluginLogTable;

  AyinReserve: AyinReserveTable;

  AyinLiquidityEvent: AyinLiquidityEventTable;

  AyinSwap: AyinSwapTable;
}
