// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.Session */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId | undefined, SessionId>;

  userId: ColumnType<UserId, UserId, UserId>;

  sessionToken: ColumnType<string, string, string>;

  expires: ColumnType<Date, Date | string, Date | string>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
