// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.Subscription */
export type SubscriptionId = string & { __brand: 'SubscriptionId' };

/** Represents the table public.Subscription */
export default interface SubscriptionTable {
  id: ColumnType<SubscriptionId, SubscriptionId | undefined, SubscriptionId>;

  userAddress: ColumnType<string, string, string>;

  amount: ColumnType<bigint, bigint, bigint>;

  startAt: ColumnType<Date, Date | string, Date | string>;

  endAt: ColumnType<Date, Date | string, Date | string>;

  timestamp: ColumnType<Date, Date | string, Date | string>;
}

export type Subscription = Selectable<SubscriptionTable>;

export type NewSubscription = Insertable<SubscriptionTable>;

export type SubscriptionUpdate = Updateable<SubscriptionTable>;
