// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.User */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.User */
export default interface UserTable {
  id: ColumnType<UserId, UserId | undefined, UserId>;

  name: ColumnType<string | null, string | null, string | null>;

  email: ColumnType<string, string, string>;

  emailVerified: ColumnType<Date | null, Date | string | null, Date | string | null>;

  image: ColumnType<string | null, string | null, string | null>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
