// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.VerificationToken */
export type VerificationTokenId = string & { __brand: 'VerificationTokenId' };

/** Represents the table public.VerificationToken */
export default interface VerificationTokenTable {
  id: ColumnType<VerificationTokenId, VerificationTokenId | undefined, VerificationTokenId>;

  userId: ColumnType<UserId, UserId, UserId>;

  identifier: ColumnType<string, string, string>;

  token: ColumnType<string, string, string>;

  expires: ColumnType<Date, Date | string, Date | string>;
}

export type VerificationToken = Selectable<VerificationTokenTable>;

export type NewVerificationToken = Insertable<VerificationTokenTable>;

export type VerificationTokenUpdate = Updateable<VerificationTokenTable>;
